version: '3.8'

services:
  runner:
    build: .
    container_name: gitlab-runner
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /home/ubuntu/runner/data:/app/data
      - /home/ubuntu/repos:/app/repos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  gitlab-runner-data:
  gitlab-runner-repos:
