version: '3.8'
services:
  runner:
    build: .
    container_name: gitlab-runner
    user: 0:0
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin
    volumes:
      - /home/ubuntu/runner/data:/app/data
      - /home/ubuntu/repos:/app/repos
    restart: unless-stopped
    networks:
      - internal
    labels:
      - 'traefik.http.middlewares.mybasicauth.basicauth.users=sysprak:$2y$05$jfSXhK3o2lHwDHgVAmd6Helr/K0Wh/pLmDO82hsWkwHl0EN3MWppy'

volumes:
  gitlab-runner-data:
  gitlab-runner-repos:

networks:
  internal:
    driver: bridge
